const SNAPSHOTS_SPREADSHEET_ID = ""
const SNAPSHOTS_SPREADSHEET_NAME = ""
const SNAPSHOTS_CREATED_DATE_COLUMN = 0
const SNAPSHOTS_EVENT_DATE_COLUMN = 0
const SNAPSHOTS_EVENT_NAME_COLUMN = 0
const SNAPSHOTS_SNAPSHOT_VERSION_COLUMN = 0
const SNAPSHOTS_BASE64_COLUMN = 0



